LIBNAME AESDTM XPORT "&SDTMPATH/ae.xpt";

DATA ADSL_V1;
    SET ADAM.ADSL_V1;
RUN;

DATA AE_SDTM;
	SET AESDTM.AE;
RUN;

/*==========================================================================
				Derivation Chian 1
===========================================================================*/

/*Step 1 Derive variales directly from ADSL_V1 */
DATA ADSL_STEP_1;
	SET ADSL_V1;
	TRTA = TRT01A;
	TRTAN = TRT01AN;
	KEEP STUDYID SITEID USUBJID TRTA TRTAN AGE AGEGR1 AGEGR1N RACE RACEN SEX SAFFL TRTSDT TRTEDT;
RUN;

/*Step 2 Derive variales directly from AE*/
DATA AE_STEP_2;
	SET AE_SDTM;
	
	KEEP STUDYID USUBJID AELLT AELLTCD AEPTCD AEHLT AEHLTCD AEHLGT AEHLGTCD AEBODSYS 
	AESOC AESOCCD AESEV AESER AESCAN AESCONG AESDISAB AESDTH AESHOSP AESLIFE AESOD AEREL
	AEACN AEOUT AESEQ AESTDTC AEENDTC AEDECOD AETERM
	;
RUN;

/*Step 3 Merge ADSL_STEP_1 and ADAE_STEP_2*/
PROC SORT DATA = ADSL_STEP_1;
	BY STUDYID USUBJID;
RUN;

PROC SORT DATA = AE_STEP_2;
	BY STUDYID USUBJID;
RUN;

DATA ADAE_STEP_3;
	MERGE ADSL_STEP_1 (IN = A) AE_STEP_2 (IN = B);
	BY STUDYID USUBJID;
	IF B = 1;
RUN;

/*==========================================================================
				Derivation Chian 2
===========================================================================*/
/*Step 4 Derive ASTDT, ASTDTF*/
DATA DERIVE_FROM_AESTDTC;
	SET ADAE_STEP_3;
	KEEP STUDYID USUBJID TRTSDT AESTDTC AESEQ;
RUN;

DATA DERIVE_ASTDT_ASTDTF;
	SET DERIVE_FROM_AESTDTC;
	
	LENGTH ASTDTF $1;
	
	IF LENGTH(STRIP(SUBSTR(AESTDTC, 1, 10))) = 10 THEN DO;
		ASTDT = INPUT(AESTDTC, YYMMDD10.);
		ASTDTF = '';
	END;
	ELSE IF LENGTH(STRIP(SUBSTR(AESTDTC, 1, 10))) = 7 THEN DO;
		ASTDT = INPUT(STRIP(AESTDTC)||'-01', YYMMDD10.);
		ASTDTF = 'D';
	END;
	ELSE IF LENGTH(STRIP(SUBSTR(AESTDTC, 1, 10))) < 7 THEN DO;
		ASTDT = .;
		ASTDTF = '';
	END;
	
	IF ASTDT >= TRTSDT AND NOT MISSING(ASTDT) THEN ASTDY = ASTDT - TRTSDT + 1;
	ELSE IF TRTSDT > ASTDT AND NOT MISSING(ASTDT) THEN ASTDY = ASTDT - TRTSDT;
	
	FORMAT ASTDT DATE9.;
	
	LABEL 
	ASTDT = 'Analysis Start Date'
	ASTDTF = 'Analysis Start Date Imputation Flag';
RUN;

/*Check the data STEP 4*/
PROC FREQ DATA = DERIVE_ASTDT_ASTDTF;
	TABLES ASTDTF*AESTDTC*ASTDT/LIST MISSING;
RUN;

/*Merge the data STEP 4*/
PROC SORT DATA = adae_step_3;
	BY STUDYID USUBJID AESEQ;
RUN;

PROC SORT DATA = DERIVE_ASTDT_ASTDTF(KEEP = STUDYID USUBJID ASTDT ASTDTF ASTDY AESEQ);
	BY STUDYID USUBJID AESEQ;
RUN;

DATA ADAE_STEP_4_ASTDT;
	MERGE ADAE_STEP_3 (IN = A) DERIVE_ASTDT_ASTDTF(IN = B);
	BY STUDYID USUBJID AESEQ;
	IF A = 1;
RUN;


/*Step 5 Derive AENDT, AENDY*/
DATA DERIVE_FROM_AEENDTC;
	SET ADAE_STEP_4_ASTDT;
	KEEP STUDYID USUBJID TRTSDT AEENDTC AESEQ;
RUN;

PROC FREQ DATA = DERIVE_FROM_AEENDTC;
	TABLES TRTSDT/MISSING;
RUN;

DATA DERIVE_AENDT_AENDY;
	SET DERIVE_FROM_AEENDTC;
	
	IF NOT MISSING(AEENDTC)  THEN AENDT = INPUT(AEENDTC, YYMMDD10.);
	ELSE AENDT = .;
	FORMAT AENDT DATE9.;
	
	IF AENDT >= TRTSDT AND NOT MISSING(AENDT) THEN AENDY = AENDT -TRTSDT + 1;
	ELSE IF TRTSDT > AENDT AND NOT MISSING(AENDT) THEN AENDY = AENDT - TRTSDT;
	
	LABEL
	AENDT = 'Analysis End Date'
	AENDY = 'Analysis End Relative Day';
RUN;
/*Check the data Step 5*/

PROC FREQ DATA = DERIVE_AENDT_AENDY;
	TABLES AENDT*AENDY / LIST MISSING;
RUN;

/*Merge the data Step 5*/
PROC SORT DATA = adae_step_4_astdt;
	BY STUDYID USUBJID AESEQ; 
RUN;

PROC SORT DATA = DERIVE_AENDT_AENDY (KEEP = STUDYID USUBJID AENDT AENDY AESEQ);
	BY STUDYID USUBJID AESEQ;
RUN;

DATA ADAE_STEP_5_AENDT;
	MERGE ADAE_STEP_4_ASTDT (IN = A) DERIVE_AENDT_AENDY(IN = B);
	BY STUDYID USUBJID AESEQ;
	IF A = 1;
RUN;

/*==========================================================================
				Derivation Chian 2
===========================================================================*/

/*Step 6 Derive TRTEMFL */
DATA DERIVE_FROM_ASTDT;
	SET adae_step_5_aendt;
	KEEP STUDYID USUBJID TRTSDT ASTDT AESEQ;
RUN;

DATA DERIVE_TRTEMFL;
	SET DERIVE_FROM_ASTDT;
	IF ASTDT >= TRTSDT AND NOT MISSING(ASTDT) THEN TRTEMFL = 'Y';
	ELSE TRTEMFL = 'N';

RUN;

/*Check the data TRTEMFL*/
PROC FREQ DATA = DERIVE_TRTEMFL;
	TABLE ASTDT*TRTSDT*TRTEMFL /LIST MISSING;
RUN;

/*Merge the data Step 6*/
PROC SORT DATA = adae_step_5_aendt;
	BY STUDYID USUBJID AESEQ;
RUN;

PROC SORT DATA = DERIVE_TRTEMFL (KEEP = STUDYID USUBJID TRTEMFL AESEQ);
	BY STUDYID USUBJID AESEQ;
RUN;

DATA ADAE_STEP_6_TRTEMFL;
	MERGE ADAE_STEP_5_AENDT(IN = A) DERIVE_TRTEMFL(IN = B);
	BY STUDYID USUBJID AESEQ;
	IF A = 1;
	LABEL TRTEMFL = 'Treatment Emergent Analysis Flag';
RUN;


/*==========================================================================
				Derivation Chian 3
===========================================================================*/

/*Step 7 Derive ADURN, ADURU */
DATA DERIVE_FROM_ASTDT_7;
	SET ADAE_STEP_6_TRTEMFL;
	KEEP STUDYID USUBJID AENDT ASTDT AESEQ ASTDTF;
RUN;

DATA DERIVE_ADURN_ADURU;
	SET DERIVE_FROM_ASTDT_7;
	LENGTH ADURN 8;
	LENGTH ADURU $3;
	
    IF MISSING(AENDT) OR MISSING(ASTDT) OR NOT MISSING(ASTDTF) THEN ADURN = .;
    ELSE ADURN = AENDT - ASTDT + 1;
	
	IF NOT MISSING(ADURN) THEN ADURU = 'DAY';
	LABEL 
	ADURN = 'AE Duration (N)'
	ADURU = 'AE Duration Units';
RUN;

PROC FREQ DATA = DERIVE_ADURN_ADURU;
	TABLES AENDT*ASTDT*ADURN*ADURU / LIST MISSING;
RUN;


/*Check the data ADURN, ADURN*/
PROC FREQ DATA = DERIVE_ADURN_ADURU;
	TABLES ADURN*ADURU / LIST MISSING;
RUN;
/*Merge the data Step 7*/
PROC SORT DATA = ADAE_STEP_6_TRTEMFL;
	BY STUDYID USUBJID AESEQ;
RUN;
PROC SORT DATA = DERIVE_ADURN_ADURU (KEEP = STUDYID USUBJID ADURN ADURU AESEQ);
	BY STUDYID USUBJID AESEQ;
RUN;

DATA ADAE_STEP_7_ADURN;
	MERGE ADAE_STEP_6_TRTEMFL (IN = A) DERIVE_ADURN_ADURU(IN = B);
	BY STUDYID USUBJID AESEQ;
	IF A = 1;
RUN;

/*==========================================================================
				Derivation Chian 4 for FL
===========================================================================*/
DATA DERIVE_FOR_FL_1;
	SET adae_step_7_adurn;
	WHERE TRTEMFL = 'Y';
RUN;

/*STEP 8 Derive AOCCFL*/
PROC SORT DATA = DERIVE_FOR_FL_1 OUT = FL_AOCCFL;
	BY USUBJID ASTDT AESEQ;
RUN;

DATA DERIVE_AOCCFL;
	SET FL_AOCCFL;
	BY USUBJID ASTDT AESEQ;
	IF FIRST.USUBJID = 1 THEN AOCCFL = 'Y';
	KEEP STUDYID USUBJID ASTDT AESEQ AOCCFL;
RUN;

PROC SORT DATA = adae_step_7_adurn;
	BY STUDYID USUBJID ASTDT AESEQ;
RUN;

PROC SORT DATA = DERIVE_AOCCFL;
	BY STUDYID USUBJID ASTDT AESEQ;
RUN;

DATA ADAE_STEP_8_AOCCFL;
	MERGE adae_step_7_adurn(IN = A) DERIVE_AOCCFL(IN = B);
	BY STUDYID USUBJID ASTDT AESEQ;
	IF A = 1;
RUN;

/*STEP 9 Derive AOCCSFL*/
PROC SORT DATA = DERIVE_FOR_FL_1 OUT = FL_AOCCSFL;
	BY USUBJID AEBODSYS ASTDT AESEQ;
RUN;

DATA DERIVE_AOCCSFL;
	SET FL_AOCCSFL;
	BY USUBJID AEBODSYS ASTDT AESEQ;
	IF FIRST.AEBODSYS = 1 THEN AOCCSFL = 'Y';
	KEEP STUDYID USUBJID AEBODSYS ASTDT AESEQ AOCCSFL;
RUN;

PROC SORT DATA = ADAE_STEP_8_AOCCFL;
	BY STUDYID USUBJID AEBODSYS ASTDT AESEQ;
RUN;

PROC SORT DATA = DERIVE_AOCCSFL;
	BY STUDYID USUBJID AEBODSYS ASTDT AESEQ;
RUN;

DATA ADAE_STEP_9_AOCCSFL;
	MERGE ADAE_STEP_8_AOCCFL(IN = A) DERIVE_AOCCSFL(IN = B);
	BY STUDYID USUBJID AEBODSYS ASTDT AESEQ;
	IF A = 1;
RUN;


/*STEP 10 Derive AOCCPFL*/
PROC SORT DATA = DERIVE_FOR_FL_1 OUT = FL_AOCCPFL;
	BY USUBJID AEBODSYS AEDECOD ASTDT AESEQ;
RUN;

DATA DERIVE_AOCCPFL;
	SET FL_AOCCPFL;
	BY USUBJID AEBODSYS AEDECOD ASTDT AESEQ;
	IF FIRST.AEDECOD = 1 THEN AOCCPFL = 'Y';
	KEEP STUDYID USUBJID AEBODSYS AEDECOD ASTDT AESEQ AOCCPFL;
RUN;

PROC SORT DATA = DERIVE_AOCCPFL;
	BY STUDYID USUBJID AEBODSYS AEDECOD ASTDT AESEQ;
RUN;

PROC SORT DATA = ADAE_STEP_9_AOCCSFL;
	BY STUDYID USUBJID AEBODSYS AEDECOD ASTDT AESEQ;
RUN;

DATA ADAE_STEP_10_AOCCPFL;
	MERGE ADAE_STEP_9_AOCCSFL(IN = A) DERIVE_AOCCPFL(IN = B);
	BY STUDYID USUBJID AEBODSYS AEDECOD ASTDT AESEQ;
	IF A = 1;
RUN;

/*STEP 11 Derive AOCC02FL*/
DATA DERIVE_FOR_FL_2;
	SET adae_step_7_adurn;
	WHERE TRTEMFL = 'Y' AND AESER = 'Y';
RUN;

PROC SORT DATA = DERIVE_FOR_FL_2 OUT = FL_AOCC02FL;
	BY USUBJID ASTDT AESEQ;
RUN;

DATA DERIVE_AOCC02FL;
	SET FL_AOCC02FL;
	BY USUBJID ASTDT AESEQ;
	IF FIRST.USUBJID = 1 THEN AOCC02FL = 'Y';
	KEEP STUDYID USUBJID ASTDT AESEQ AOCC02FL;
RUN;

PROC SORT DATA = DERIVE_AOCC02FL;
	BY STUDYID USUBJID ASTDT AESEQ;
RUN;

PROC SORT DATA = ADAE_STEP_10_AOCCPFL;
	BY STUDYID USUBJID ASTDT AESEQ;
RUN;

DATA ADAE_STEP_11_AOCC02FL;
	MERGE ADAE_STEP_10_AOCCPFL(IN = A) DERIVE_AOCC02FL(IN = B);
	BY STUDYID USUBJID ASTDT AESEQ;
	IF A = 1;
RUN;

/*STEP 12 Derive AOCC03FL*/
PROC SORT DATA = DERIVE_FOR_FL_2 OUT = FL_AOCC03FL;
	BY USUBJID AEBODSYS ASTDT AESEQ;
RUN;

DATA DERIVE_AOCC03FL;
	SET FL_AOCC03FL;
	BY USUBJID AEBODSYS ASTDT AESEQ;
	IF FIRST.AEBODSYS = 1 THEN AOCC03FL = 'Y';
	KEEP STUDYID USUBJID AEBODSYS AESEQ AOCC03FL;
RUN;

PROC SORT DATA = DERIVE_AOCC03FL;
	BY STUDYID USUBJID AEBODSYS AESEQ;
RUN;

PROC SORT DATA = ADAE_STEP_11_AOCC02FL;
	BY STUDYID USUBJID AEBODSYS AESEQ;
RUN;

DATA ADAE_STEP_12_AOCC03FL;
	MERGE ADAE_STEP_11_AOCC02FL(IN = A) DERIVE_AOCC03FL (IN = B);
	BY STUDYID USUBJID AEBODSYS AESEQ;
	IF A = 1;
RUN;

/*STEP 13 Derive AOCC04FL*/
PROC SORT DATA = DERIVE_FOR_FL_2 OUT = FL_AOCC04FL;
	BY USUBJID AEBODSYS AEDECOD ASTDT AESEQ;
RUN;

DATA DERIVE_AOCC04FL;
	SET FL_AOCC04FL;
	BY USUBJID AEBODSYS AEDECOD ASTDT AESEQ;
	IF FIRST.AEDECOD = 1 THEN AOCC04FL = 'Y';
	KEEP STUDYID USUBJID AEBODSYS AEDECOD ASTDT AESEQ AOCC04FL;
RUN;

PROC SORT DATA = DERIVE_AOCC04FL;
	BY STUDYID USUBJID AEBODSYS AEDECOD ASTDT AESEQ;
RUN;

PROC SORT DATA = ADAE_STEP_12_AOCC03FL;
	BY STUDYID USUBJID AEBODSYS AEDECOD ASTDT AESEQ;
RUN;

DATA ADAE_STEP_13_AOCC04FL;
	MERGE ADAE_STEP_12_AOCC03FL(IN = A) DERIVE_AOCC04FL(IN = B);
	BY STUDYID USUBJID AEBODSYS AEDECOD ASTDT AESEQ;
	IF A = 1;
RUN;


/*STEP 14 Derive CQ01NAM*/
DATA ADAE_STEP_14_CQ01NAM;
	SET ADAE_STEP_13_AOCC04FL;
	LENGTH CQ01NAM $19;

	IF (INDEX(AEDECOD,'APPLICATION')
	OR INDEX(AEDECOD,'DERMATITIS')
	OR INDEX(AEDECOD,'ERYTHEMA')
	OR INDEX(AEDECOD,'BLISTER')
	OR AEBODSYS = 'SKIN AND SUBCUTANEOUS TISSUE DISORDERS')
	AND AEDECOD NOT IN ('COLD SWEAT', 'HYPERHIDROSIS','ALOPECIA')
	THEN CQ01NAM = 'DERMATOLOGIC EVENTS';
	ELSE CQ01NAM = '';

	LABEL CQ01NAM = 'Customized Query 01 Name';
RUN;


/*STEP 15 Derive AOCC01FL*/

PROC SORT DATA = ADAE_STEP_14_CQ01NAM OUT = FL_AOCC01FL;
	BY USUBJID ASTDT AESEQ;
	WHERE CQ01NAM = 'DERMATOLOGIC EVENTS' AND TRTEMFL = 'Y';
RUN;

DATA DERIVE_AOCC01FL;
	SET FL_AOCC01FL;
	BY USUBJID ASTDT AESEQ;
	IF FIRST.USUBJID = 1 THEN AOCC01FL = 'Y';
	KEEP STUDYID USUBJID ASTDT AESEQ AOCC01FL;
RUN;

PROC SORT DATA = DERIVE_AOCC01FL;
	BY STUDYID USUBJID ASTDT AESEQ;
RUN;

PROC SORT DATA = ADAE_STEP_14_CQ01NAM;
	BY STUDYID USUBJID ASTDT AESEQ;
RUN;

DATA ADAE_STEP_15_AOCC01FL;
	MERGE ADAE_STEP_14_CQ01NAM(IN = A) DERIVE_AOCC01FL(IN = B);
	BY STUDYID USUBJID ASTDT AESEQ;
	IF A = 1;
RUN;

/*==========================================================================
					Compare ADAE_STD and ADAE_final
===========================================================================*/
LIBNAME ADSL XPORT "&REFPATH/adae.xpt";

DATA ADAE_STD;
    SET ADSL.adae;
RUN;

DATA ADAE_FINAL;
	LENGTH STUDYID $12 SITEID $3 USUBJID $11 TRTA $20
	       AGEGR1 $5 RACE $32 SEX $1 SAFFL $1
	       ASTDTF $1
	       ADURU $3
	       AETERM $46 AELLT $46 AEDECOD $46 AEHLT $8 AEHLGT $9
	       AEBODSYS $67 AESOC $67
	       AESEV $8 AESER $1 AESCAN $1 AESCONG $1 AESDISAB $1
	       AESDTH $1 AESHOSP $1 AESLIFE $1 AESOD $1
	       AEREL $8 AEACN $1 AEOUT $26
	       TRTEMFL $1 AOCCFL $1 AOCCSFL $1 AOCCPFL $1
	       AOCC02FL $1 AOCC03FL $1 AOCC04FL $1
	       CQ01NAM $19 AOCC01FL $1;

	RETAIN STUDYID SITEID USUBJID TRTA TRTAN AGE AGEGR1 AGEGR1N
           RACE RACEN SEX SAFFL TRTSDT TRTEDT
           ASTDT ASTDTF ASTDY AENDT AENDY ADURN ADURU
           AETERM AELLT AELLTCD AEDECOD AEPTCD
           AEHLT AEHLTCD AEHLGT AEHLGTCD AEBODSYS AESOC AESOCCD
           AESEV AESER AESCAN AESCONG AESDISAB AESDTH AESHOSP
           AESLIFE AESOD AEREL AEACN AEOUT AESEQ
           TRTEMFL AOCCFL AOCCSFL AOCCPFL
           AOCC02FL AOCC03FL AOCC04FL
           CQ01NAM AOCC01FL;

	LABEL STUDYID  = 'Study Identifier'
	      SITEID   = 'Study Site Identifier'
	      USUBJID  = 'Unique Subject Identifier'
	      TRTA     = 'Actual Treatment'
	      TRTAN    = 'Actual Treatment (N)'
	      AGE      = 'Age'
	      AGEGR1   = 'Pooled Age Group 1'
	      AGEGR1N  = 'Pooled Age Group 1 (N)'
	      RACE     = 'Race'
	      RACEN    = 'Race (N)'
	      SEX      = 'Sex'
	      SAFFL    = 'Safety Population Flag'
	      TRTSDT   = 'Date of First Exposure to Treatment'
	      TRTEDT   = 'Date of Last Exposure to Treatment'
	      ASTDT    = 'Analysis Start Date'
	      ASTDTF   = 'Analysis Start Date Imputation Flag'
	      ASTDY    = 'Analysis Start Relative Day'
	      AENDT    = 'Analysis End Date'
	      AENDY    = 'Analysis End Relative Day'
	      ADURN    = 'AE Duration (N)'
	      ADURU    = 'AE Duration Units'
	      AETERM   = 'Reported Term for the Adverse Event'
	      AELLT    = 'Lowest Level Term'
	      AELLTCD  = 'Lowest Level Term Code'
	      AEDECOD  = 'Dictionary-Derived Term'
	      AEPTCD   = 'Preferred Term Code'
	      AEHLT    = 'High Level Term'
	      AEHLTCD  = 'High Level Term Code'
	      AEHLGT   = 'High Level Group Term'
	      AEHLGTCD = 'High Level Group Term Code'
	      AEBODSYS = 'Body System or Organ Class'
	      AESOC    = 'Primary System Organ Class'
	      AESOCCD  = 'Primary System Organ Class Code'
	      AESEV    = 'Severity/Intensity'
	      AESER    = 'Serious Event'
	      AESCAN   = 'Involves Cancer'
	      AESCONG  = 'Congenital Anomaly or Birth Defect'
	      AESDISAB = 'Persist or Signif Disability/Incapacity'
	      AESDTH   = 'Results in Death'
	      AESHOSP  = 'Requires or Prolongs Hospitalization'
	      AESLIFE  = 'Is Life Threatening'
	      AESOD    = 'Occurred with Overdose'
	      AEREL    = 'Causality'
	      AEACN    = 'Action Taken with Study Treatment'
	      AEOUT    = 'Outcome of Adverse Event'
	      AESEQ    = 'Sequence Number'
	      TRTEMFL  = 'Treatment Emergent Analysis Flag'
	      AOCCFL   = '1st Occurrence of Any AE Flag'
	      AOCCSFL  = '1st Occurrence of SOC Flag'
	      AOCCPFL  = '1st Occurrence of Preferred Term Flag'
	      AOCC02FL = '1st Occurrence 02 Flag for Serious'
	      AOCC03FL = '1st Occurrence 03 Flag for Serious SOC'
	      AOCC04FL = '1st Occurrence 04 Flag for Serious PT'
	      CQ01NAM  = 'Customized Query 01 Name'
	      AOCC01FL = '1st Occurrence 01 Flag for CQ01'
	;

	SET ADAE_STEP_15_AOCC01FL;

	KEEP STUDYID SITEID USUBJID TRTA TRTAN AGE AGEGR1 AGEGR1N
           RACE RACEN SEX SAFFL TRTSDT TRTEDT
           ASTDT ASTDTF ASTDY AENDT AENDY ADURN ADURU
           AETERM AELLT AELLTCD AEDECOD AEPTCD
           AEHLT AEHLTCD AEHLGT AEHLGTCD AEBODSYS AESOC AESOCCD
           AESEV AESER AESCAN AESCONG AESDISAB AESDTH AESHOSP
           AESLIFE AESOD AEREL AEACN AEOUT AESEQ
           TRTEMFL AOCCFL AOCCSFL AOCCPFL
           AOCC02FL AOCC03FL AOCC04FL
           CQ01NAM AOCC01FL;
RUN;

PROC SORT DATA = ADAE_STD; 
	BY STUDYID USUBJID AETERM ASTDT AESEQ;
RUN;

PROC SORT DATA = ADAE_FINAL;
	BY STUDYID USUBJID AETERM ASTDT AESEQ;
RUN;

PROC COMPARE BASE = adae_std COMPARE = ADAE_FINAL;
	ID STUDYID USUBJID AETERM ASTDT AESEQ;
RUN;


PROC PRINT DATA = ADAE_FINAL (KEEP = USUBJID ADURU ADURN ASTDY ASTDTF ASTDT);
	WHERE USUBJID = '01-716-1418';
RUN;

DATA ADAM.ADAE_V1;
    SET ADAE_FINAL;
RUN;


DATA CHK;
    SET ADAE_STD;
    ADURN_MISS = MISSING(ADURN);
RUN;

PROC FREQ DATA = CHK;
    TABLES ASTDTF * ADURN_MISS / LIST MISSING;
RUN;

