LIBNAME ADAM "/home/u63793342/sasuser.v94";
LIBNAME LBSDTM XPORT "/home/u63793342/sasuser.v94/lb.xpt";
LIBNAME ADLBH XPORT "/home/u63793342/sasuser.v94/adlbh.xpt";

DATA ADSL_V1;
    SET ADAM.ADSL_V1;
RUN;

DATA lb_sdtm;
	SET LBSDTM.lb;
RUN;

DATA adlbh_std;
	SET ADLBH.adlbh;
RUN;


PROC SQL;
SELECT
    STRIP(name)||'='||QUOTE(TRIM(label))
INTO :LABEL_ADLBH SEPARATED BY ' '
FROM Dictionary.columns
WHERE libname = 'WORK'
AND memname = 'ADLBH_STD'
;
QUIT;

%PUT &LABEL_ADLBH;


/*===================================================================================================
						Derivation Chain 0
==================================================================================================*/

/*Step 1 Derive variables from ADSL directly*/
DATA ADSL_STEP_1;
	LENGTH RACE $32;
	SET ADSL_V1;
	TRTP = TRT01P;
	TRTPN = TRT01PN;
	TRTA = TRT01A;
	TRTAN = TRT01AN;
	KEEP STUDYID SUBJID USUBJID TRTP TRTPN TRTA TRTAN TRTSDT TRTEDT 
	AGE AGEGR1 AGEGR1N RACE RACEN SEX SAFFL COMP24FL DSRAEFL SAFFL;
RUN;


/*Step 2 Derive variables from LB directly*/

DATA LB_STEP_2;
	LENGTH LBTESTCD $8;
	LENGTH LBNRIND $8;
	SET lb_sdtm;
	WHERE LBCAT = 'HEMATOLOGY' AND VISIT NOT IN ('AMBUL ECG REMOVAL','RETRIEVAL','BASELINE');
	KEEP STUDYID USUBJID LBSEQ LBTESTCD LBTEST LBCAT LBSTRESN LBSTRESC
	     LBSTNRLO LBSTNRHI LBNRIND LBBLFL VISITNUM VISIT LBDY LBDTC;
RUN;


/*Step 3 Create the tables for PARAM*/
DATA param_lookup;
    LENGTH PARAM $100 PARAMCD $8 PARCAT1 $5;
    INFILE DATALINES DLM='|' DSD;
    INPUT PARAM $ PARAMCD $ PARAMN PARCAT1 $;
DATALINES;
Hemoglobin (mmol/L)|HGB|1|HEM
Hematocrit|HCT|2|HEM
Ery. Mean Corpuscular Volume (fL)|MCV|3|HEM
Ery. Mean Corpuscular Hemoglobin (fmol(Fe))|MCH|4|HEM
Ery. Mean Corpuscular HGB Concentration (mmol/L)|MCHC|5|HEM
Leukocytes (GI/L)|WBC|6|HEM
Lymphocytes (GI/L)|LYM|7|HEM
Monocytes (GI/L)|MONO|8|HEM
Eosinophils (GI/L)|EOS|9|HEM
Basophils (GI/L)|BASO|10|HEM
Platelet (GI/L)|PLAT|11|HEM
Erythrocytes (TI/L)|RBC|12|HEM
Anisocytes|ANISO|13|HEM
Macrocytes|MACROCY|14|HEM
Microcytes|MICROCY|15|HEM
Poikilocytes|POIKILO|16|HEM
Polychromasia|POLYCHR|17|HEM
Hemoglobin (mmol/L) change from previous visit, relative to normal range|_HGB|101|HEM
Hematocrit change from previous visit, relative to normal range|_HCT|102|HEM
Ery. Mean Corpuscular Volume (fL) change from previous visit, relative to normal range|_MCV|103|HEM
Ery. Mean Corpuscular Hemoglobin (fmol(Fe)) change from previous visit, relative to normal range|_MCH|104|HEM
Ery. Mean Corpuscular HGB Concentration (mmol/L) change from previous visit, relative to normal rang|_MCHC|105|HEM
Leukocytes (GI/L) change from previous visit, relative to normal range|_WBC|106|HEM
Lymphocytes (GI/L) change from previous visit, relative to normal range|_LYM|107|HEM
Monocytes (GI/L) change from previous visit, relative to normal range|_MONO|108|HEM
Eosinophils (GI/L) change from previous visit, relative to normal range|_EOS|109|HEM
Basophils (GI/L) change from previous visit, relative to normal range|_BASO|110|HEM
Platelet (GI/L) change from previous visit, relative to normal range|_PLAT|111|HEM
Erythrocytes (TI/L) change from previous visit, relative to normal range|_RBC|112|HEM
Anisocytes change from previous visit, relative to normal range|_ANISO|113|HEM
Macrocytes change from previous visit, relative to normal range|_MACROCY|114|HEM
Microcytes change from previous visit, relative to normal range|_MICROCY|115|HEM
Poikilocytes change from previous visit, relative to normal range|_POIKILO|116|HEM
Polychromasia change from previous visit, relative to normal range|_POLYCHR|117|HEM
;
RUN;

/*Step 4 Merge PARAM_LOOKUP and LB Original*/
PROC SORT DATA = param_lookup;
	BY PARAMCD;
RUN;

PROC SORT DATA = LB_STEP_2 OUT = LB_STEP_2_O (RENAME = (LBTESTCD = PARAMCD));
	BY LBTESTCD;
RUN;

DATA LB_STEP_4_O;
	LENGTH PARAMCD $8; 
	MERGE LB_STEP_2_O (IN = A) param_lookup(IN = B);
	BY PARAMCD;
	IF A = 1;
RUN;

PROC SORT DATA = LB_STEP_4_O;
	BY USUBJID PARAMCD VISITNUM;
RUN;

/*Step 4A Merge PARAM_LOOKUP and LB Change*/
DATA LB_STEP_3;
	LENGTH PARAMCD $8; 
	SET LB_STEP_2;
	PARAMCD = STRIP('_'||LBTESTCD);
	DROP LBTESTCD;
RUN;


PROC SORT DATA = LB_STEP_3;
	BY PARAMCD;
RUN;

PROC SORT DATA = PARAM_LOOKUP;
	BY PARAMCD;
RUN;

DATA LB_STEP_4B_C;
	LENGTH PARAMCD $8; 
	MERGE LB_STEP_3 (IN = A) PARAM_LOOKUP;
	BY PARAMCD;
	IF A = 1;
RUN;

/*===========================================================================================
						Derivation chain 1
============================================================================================*/

/*Step 5A Derive ADY, ADT*/
DATA LB_STEP_5A_O;
	SET LB_STEP_4_O;
	ADY = LBDY;
	ADT = INPUT(SUBSTR(LBDTC, 1, 10), YYMMDD10.);
	FORMAT ADT DATE9.;
RUN;


/*Step 5B Derive ADY, ADT*/
DATA LB_STEP_5B_C;
	SET LB_STEP_4B_C;
	ADY = LBDY;
	ADT = INPUT(SUBSTR(LBDTC, 1, 10), YYMMDD10.);
	FORMAT ADT DATE9.;
RUN;


/*Step 6A Derive AVAL, A1HI, A1LO, ABLFL*/
DATA LB_STEP_6A_O;
	SET LB_STEP_5A_O;
	AVAL = LBSTRESN; 
	A1HI = LBSTNRHI;
	IF LBSTNRLO = 0 THEN A1LO = .; /*A1LO for QC*/
	ELSE A1LO = LBSTNRLO;
	IF VISITNUM = 1 THEN ABLFL = 'Y';
RUN;


/*Step 6B Derive AVAL, A1HI, A1LO, ABLFL*/
DATA LB_STEP_6B_AVAL;
	SET LB_STEP_5B_C;
	A1HI = .;
	A1LO = .; /*A1HI A1LO set missing QC*/
	ABLFL = '';
RUN;

PROC SORT DATA = LB_STEP_6B_AVAL;
	BY USUBJID PARAMCD VISITNUM;
RUN;
DATA LB_STEP_6B_C;
    SET LB_STEP_6B_AVAL;
    BY USUBJID PARAMCD VISITNUM;

    RETAIN preval;
    IF FIRST.PARAMCD THEN preval = .;

    LBSTRESN_PRIOR = preval;                               /* 先讀 */

    IF VISITNUM NE INT(VISITNUM) THEN AVAL = .;            /* 未排程訪視不計算 */
    ELSE IF LBBLFL = 'Y' THEN AVAL = .;
    ELSE AVAL = ROUND((LBSTRESN - LBSTRESN_PRIOR) / (0.5*(LBSTNRHI - LBSTNRLO)), 0.1);

    IF VISITNUM = INT(VISITNUM) THEN preval = LBSTRESN;    /* 只有排程訪視更新前一次的值 QC AVAL */

    DROP LBSTRESN_PRIOR preval;
RUN;


/*Step 7A Derive AVISIT AVISITN BASE*/
PROC SORT DATA = LB_STEP_6A_O;
	BY USUBJID PARAMCD VISITNUM;
RUN;

DATA LB_STEP_7A_O;
	SET LB_STEP_6A_O;
	LENGTH AVISIT $16;
	BY USUBJID PARAMCD VISITNUM;
	RETAIN BASE_VAL; /*BASE QC*/
	
	IF VISITNUM = 1 THEN DO;
		AVISIT = 'Baseline';
		AVISITN = 0;
	END;
	ELSE IF VISITNUM = 4 THEN DO;
		AVISIT = 'Week 2';
		AVISITN = 2;
	END;
	ELSE IF VISITNUM = 5 THEN DO;
		AVISIT = 'Week 4';
		AVISITN = 4;
	END;
	ELSE IF VISITNUM = 7 THEN DO;
		AVISIT = 'Week 6';
		AVISITN = 6;
	END;
	ELSE IF VISITNUM = 8 THEN DO;
		AVISIT = 'Week 8';
		AVISITN = 8;
	END;
	ELSE IF VISITNUM = 9 THEN DO;
		AVISIT = 'Week 12';
		AVISITN = 12;
	END;
	ELSE IF VISITNUM = 10 THEN DO;
		AVISIT = 'Week 16';
		AVISITN = 16;
	END;
	ELSE IF VISITNUM = 11 THEN DO;
		AVISIT = 'Week 20';
		AVISITN = 20;
	END;
	ELSE IF VISITNUM = 12 THEN DO;
		AVISIT = 'Week 24';
		AVISITN = 24;
	END;
	ELSE IF VISITNUM = 13 THEN DO;
		AVISIT = 'Week 26';
		AVISITN = 26;
	END;
	IF FIRST.PARAMCD = 1 THEN BASE_VAL = .;
	IF ABLFL = 'Y' THEN BASE_VAL = LBSTRESN;
		BASE = BASE_VAL;
	DROP BASE_VAL;
RUN;

PROC FREQ DATA = LB_STEP_7A_O;
	TABLES VISITNUM * VISIT * AVISITN * AVISIT / LIST MISSING;
RUN;


/*Step 7B Derive AVISIT AVISITN BASE*/

DATA LB_STEP_7B_C;
	SET LB_STEP_6B_C;
	IF VISITNUM = 1 THEN DO;
		AVISIT = 'Baseline';
		AVISITN = 0;
	END;
	ELSE IF VISITNUM = 4 THEN DO;
		AVISIT = 'Week 2';
		AVISITN = 2;
	END;
	ELSE IF VISITNUM = 5 THEN DO;
		AVISIT = 'Week 4';
		AVISITN = 4;
	END;
	ELSE IF VISITNUM = 7 THEN DO;
		AVISIT = 'Week 6';
		AVISITN = 6;
	END;
	ELSE IF VISITNUM = 8 THEN DO;
		AVISIT = 'Week 8';
		AVISITN = 8;
	END;
	ELSE IF VISITNUM = 9 THEN DO;
		AVISIT = 'Week 12';
		AVISITN = 12;
	END;
	ELSE IF VISITNUM = 10 THEN DO;
		AVISIT = 'Week 16';
		AVISITN = 16;
	END;
	ELSE IF VISITNUM = 11 THEN DO;
		AVISIT = 'Week 20';
		AVISITN = 20;
	END;
	ELSE IF VISITNUM = 12 THEN DO;
		AVISIT = 'Week 24';
		AVISITN = 24;
	END;
	ELSE IF VISITNUM = 13 THEN DO;
		AVISIT = 'Week 26';
		AVISITN = 26;
	END;
	
	BASE = .;
RUN;

PROC FREQ DATA = LB_STEP_7B_C;
	TABLES VISITNUM * VISIT * AVISITN * AVISIT / LIST MISSING;
RUN;

/*===========================================================================================
						Derivation chain 2
============================================================================================*/
/*Step 8A Derive CHG, R2A1LO, R2A1HI, BR2A1LO, BR2A1HI*/
PROC SORT DATA = LB_STEP_7A_O;
	BY USUBJID PARAMCD VISITNUM;
RUN;


DATA LB_STEP_8A_O;
	SET LB_STEP_7A_O;
	BY USUBJID PARAMCD VISITNUM;
	RETAIN BR2A1LO_VAL BR2A1HI_VAL;
	
	
	
	IF ABLFL NE 'Y' AND NMISS(AVAL, BASE) = 0 THEN CHG = AVAL - BASE; /* CHG for QC*/
	IF A1LO ^= 0 AND NOT MISSING(A1LO) THEN R2A1LO = AVAL / A1LO;
	IF A1HI ^= 0 AND NOT MISSING(A1HI) THEN R2A1HI = AVAL / A1HI;
	
	IF FIRST.PARAMCD = 1 THEN DO;
		BR2A1LO_VAL = .;
		BR2A1HI_VAL = .;
	END;
	
	IF ABLFL = 'Y' AND A1LO ^= 0 AND NOT MISSING(A1LO) THEN BR2A1LO_VAL = AVAL / A1LO;
	IF ABLFL = 'Y' AND A1HI ^= 0 AND NOT MISSING(A1HI) THEN BR2A1HI_VAL = AVAL / A1HI;
	
	BR2A1LO = BR2A1LO_VAL;
	BR2A1HI = BR2A1HI_VAL;  /*QC for BR2A1LO*/
	DROP BR2A1LO_VAL BR2A1HI_VAL;
RUN;

/*Step 8B Derive CHG, R2A1LO, R2A1HI, BR2A1LO, BR2A1HI*/

DATA LB_STEP_8B_C;
	SET LB_STEP_7B_C;
	
	IF A1LO ^= 0 AND NOT MISSING(A1LO) THEN R2A1LO = AVAL / A1LO;
	IF A1HI ^= 0 AND NOT MISSING(A1HI) THEN R2A1HI = AVAL / A1HI;
	BR2A1LO = .;
	BR2A1HI = .;
	CHG = .;
RUN;


/*Step 9A Derive ALBTRVAL, ANL01FL*/
DATA LB_STEP_9A_ALBTRVAL;
	SET LB_STEP_8A_O;
	IF NMISS(LBSTRESN, LBSTNRLO, LBSTNRHI) = 0 
		THEN ALBTRVAL = MAX((1.5*LBSTNRHI)-LBSTRESN, LBSTRESN-(LBSTNRLO*0.5));
RUN;

PROC SORT DATA = LB_STEP_9A_ALBTRVAL OUT = SORT_ALBTRVAL (KEEP = STUDYID USUBJID PARAMCD VISITNUM ALBTRVAL);
	BY USUBJID PARAMCD DESCENDING ALBTRVAL VISITNUM;
	WHERE VISITNUM IN (4,5,7,8,9,10,11,12);
RUN;

DATA MERGE_ALBTRVAL;
	SET SORT_ALBTRVAL;
	BY USUBJID PARAMCD DESCENDING ALBTRVAL VISITNUM;
	IF FIRST.PARAMCD = 1 AND NOT MISSING(ALBTRVAL) THEN ANL01FL = 'Y';
	KEEP STUDYID USUBJID PARAMCD VISITNUM ANL01FL ALBTRVAL;
RUN;

PROC SORT DATA = MERGE_ALBTRVAL;
	BY STUDYID USUBJID PARAMCD VISITNUM;
RUN;

PROC SORT DATA = LB_STEP_9A_ALBTRVAL;
	BY STUDYID USUBJID PARAMCD VISITNUM;
RUN;

DATA LB_STEP_9A_O;
	MERGE LB_STEP_9A_ALBTRVAL(IN = A) MERGE_ALBTRVAL(IN = B);
	BY STUDYID USUBJID PARAMCD VISITNUM;
	IF A = 1;
RUN;


/*Step 9B Derive ALBTRVAL, ANL01FL*/
DATA LB_STEP_9B_ALBTRVAL;
	SET LB_STEP_8B_C;
	IF NMISS(LBSTRESN, LBSTNRLO, LBSTNRHI) = 0 
		THEN ALBTRVAL = MAX((1.5*LBSTNRHI)-LBSTRESN, LBSTRESN-(LBSTNRLO*0.5));
		
	IF MISSING(AVAL) THEN AVAL_ABS= .;
	ELSE AVAL_ABS = ABS(AVAL);
RUN;

PROC SORT DATA = LB_STEP_9B_ALBTRVAL OUT = SORT_ALBTRVAL_B (KEEP = STUDYID USUBJID PARAMCD VISITNUM AVAL AVAL_ABS);
	BY USUBJID PARAMCD DESCENDING AVAL_ABS VISITNUM;
	WHERE VISITNUM IN (4,5,7,8,9,10,11,12);
RUN;

DATA MERGE_ALBTRVAL_B;
	SET SORT_ALBTRVAL_B;
	BY USUBJID PARAMCD DESCENDING AVAL_ABS VISITNUM;
	IF FIRST.PARAMCD = 1 AND NOT MISSING(AVAL_ABS) THEN ANL01FL = 'Y';
	KEEP STUDYID USUBJID PARAMCD VISITNUM ANL01FL;
RUN;

PROC FREQ DATA = MERGE_ALBTRVAL_B;
	TABLES ANL01FL/ LIST MISSING;
RUN;

PROC SORT DATA = MERGE_ALBTRVAL_B;
	BY STUDYID USUBJID PARAMCD VISITNUM;
RUN;

PROC SORT DATA = LB_STEP_9B_ALBTRVAL;
	BY STUDYID USUBJID PARAMCD VISITNUM;
RUN;

DATA LB_STEP_9B_C;
	MERGE LB_STEP_9B_ALBTRVAL(IN = A) MERGE_ALBTRVAL_B(IN = B);
	BY STUDYID USUBJID PARAMCD VISITNUM;
	IF A = 1;
	DROP AVAL_ABS;
RUN;

PROC FREQ DATA = LB_STEP_9B_C;
	TABLES ANL01FL /MISSING;
RUN;

/*Step 10A Derive ANRIND, BNRIND*/

DATA LB_STEP_10A_BNRIND;
	SET LB_STEP_9A_O;
	
	IF MISSING(AVAL) OR NMISS(LBSTNRLO, LBSTNRHI) > 0 THEN ANRIND = ' ';
	ELSE IF AVAL < (0.5*LBSTNRLO)  THEN ANRIND = 'L';
	ELSE IF AVAL > (1.5*LBSTNRHI)  THEN ANRIND = 'H';
	ELSE ANRIND = 'N';
	
	IF ABLFL = 'Y' THEN BNRIND_BASE = ANRIND;
	
RUN;


/* ANRIND 驗證實驗開關:1 = 模擬參考資料的寫法(僅驗證用);0 = 正式寫法 */
%LET ANRIND_EXP = 1;

DATA LB_STEP_10A_BNRIND;
    SET LB_STEP_9A_O;

    IF MISSING(AVAL) OR (&ANRIND_EXP = 0 AND NMISS(LBSTNRLO, LBSTNRHI) > 0) THEN ANRIND = ' ';
    ELSE IF AVAL < (0.5*LBSTNRLO) THEN ANRIND = 'L';
    ELSE IF AVAL > (1.5*LBSTNRHI) THEN ANRIND = 'H';
    ELSE ANRIND = 'N';

    IF ABLFL = 'Y' THEN BNRIND_BASE = ANRIND;
RUN;

PROC SORT DATA = LB_STEP_10A_BNRIND;
	BY USUBJID PARAMCD VISITNUM;
RUN;


DATA LB_STEP_10A_O;
	SET LB_STEP_10A_BNRIND;
	BY USUBJID PARAMCD VISITNUM;
	
	RETAIN BNRIND;
	IF FIRST.PARAMCD = 1 THEN BNRIND = '';
	IF ABLFL = 'Y' THEN BNRIND = BNRIND_BASE;
	
RUN;



/*Step 10B Derive ANRIND, BNRIND*/

DATA LB_STEP_10B_C;
	SET LB_STEP_9B_C;
	
	IF MISSING(AVAL) OR LBBLFL = 'Y' THEN ANRIND = ' ';
	ELSE IF AVAL < -1  THEN ANRIND = 'L';
	ELSE IF AVAL > 1  THEN ANRIND = 'H';
	ELSE ANRIND = 'N';
	
	BNRIND = ' ';
	
RUN;

/*Step 11A Derive ANETMTFL*/

PROC SORT DATA = LB_STEP_10A_O OUT = LB_STEP_11A_ANETMTFL (KEEP = USUBJID PARAMCD VISITNUM);
	BY USUBJID PARAMCD VISITNUM;
	WHERE VISITNUM IN (4,5,7,8,9,10,11,12);
RUN;

DATA MERGE_ANETMTFL;
	SET LB_STEP_11A_ANETMTFL;
	BY USUBJID PARAMCD VISITNUM;
	IF VISITNUM = 12 THEN AENTMTFL = 'Y';
	ELSE IF LAST.PARAMCD = 1 THEN AENTMTFL = 'Y';
	KEEP USUBJID PARAMCD VISITNUM AENTMTFL;
RUN;

PROC SORT DATA = MERGE_ANETMTFL;
	BY USUBJID PARAMCD VISITNUM;
RUN;

PROC SORT DATA = LB_STEP_10A_O;
	BY USUBJID PARAMCD VISITNUM;
RUN;

DATA LB_STEP_11A_O;
	MERGE LB_STEP_10A_O (IN = A) MERGE_ANETMTFL(IN = B);
	BY USUBJID PARAMCD VISITNUM;
	IF A = 1;
RUN;



/*Step 11B Derive ANETMTFL*/

PROC SORT DATA = LB_STEP_10B_C OUT = LB_STEP_11B_ANETMTFL (KEEP = USUBJID PARAMCD VISITNUM);
	BY USUBJID PARAMCD VISITNUM;
	WHERE VISITNUM IN (4,5,7,8,9,10,11,12);
RUN;

DATA MERGE_ANETMTFL_B;
	SET LB_STEP_11B_ANETMTFL;
	BY USUBJID PARAMCD VISITNUM;
	IF VISITNUM = 12 THEN AENTMTFL = 'Y';
	ELSE IF LAST.PARAMCD = 1 THEN AENTMTFL = 'Y';
	KEEP USUBJID PARAMCD VISITNUM AENTMTFL;
RUN;

PROC SORT DATA = MERGE_ANETMTFL_B;
	BY USUBJID PARAMCD VISITNUM;
RUN;

PROC SORT DATA = LB_STEP_10B_C;
	BY USUBJID PARAMCD VISITNUM;
RUN;

DATA LB_STEP_11B_C;
	MERGE LB_STEP_10B_C (IN = A) MERGE_ANETMTFL_B(IN = B);
	BY USUBJID PARAMCD VISITNUM;
	IF A = 1;
RUN;

/*===============================================================================================
							Stack two datasets
================================================================================================*/
/*Step 12 Stack two datasets*/
DATA LB_STEP_12;
	LENGTH AVISIT $16;
	SET LB_STEP_11B_C LB_STEP_11A_O;
RUN;

/*Step 13 Merge the two data, LB and ADSL*/

PROC SORT DATA = LB_STEP_12;
	BY STUDYID USUBJID ;
RUN;

PROC SORT DATA = ADSL_STEP_1;
	BY STUDYID USUBJID;
RUN;

DATA LB_STEP_13;
	LENGTH AVISIT $16;
	RETAIN STUDYID SUBJID USUBJID TRTP TRTPN TRTA TRTAN TRTSDT TRTEDT AGE AGEGR1
	 AGEGR1N RACE RACEN SEX COMP24FL DSRAEFL SAFFL AVISIT AVISITN ADY ADT VISIT VISITNUM
	 PARAM PARAMCD PARAMN PARCAT1 AVAL BASE CHG A1LO A1HI R2A1LO R2A1HI BR2A1LO BR2A1HI ANL01FL ALBTRVAL ANRIND BNRIND
	 ABLFL AENTMTFL LBSEQ LBNRIND LBSTRESN;
	 
	MERGE LB_STEP_12(IN = A) ADSL_STEP_1(IN = B);
	BY STUDYID USUBJID;
	IF A = 1;
	AVISIT = RIGHT(AVISIT);
	
	LABEL &LABEL_ADLBH;
	FORMAT ADY 3.;
	KEEP STUDYID SUBJID USUBJID TRTP TRTPN TRTA TRTAN TRTSDT TRTEDT AGE AGEGR1
	 AGEGR1N RACE RACEN SEX COMP24FL DSRAEFL SAFFL AVISIT AVISITN ADY ADT VISIT VISITNUM
	 PARAM PARAMCD PARAMN PARCAT1 AVAL BASE CHG A1LO A1HI R2A1LO R2A1HI BR2A1LO BR2A1HI ANL01FL ALBTRVAL ANRIND BNRIND
	 ABLFL AENTMTFL LBSEQ LBNRIND LBSTRESN;
RUN;

/*Step 14 Add the data for pseudo variable */

DATA FOR_EOT;
	SET LB_STEP_13;
	WHERE AENTMTFL = 'Y';
	AVISIT = 'End of Treatment';
	AVISITN = 99;
RUN;

DATA LB_STEP_14;
	SET LB_STEP_13 FOR_EOT;
RUN;


PROC SQL;
SELECT name
FROM Dictionary.columns
WHERE libname = 'WORK'
AND memname = 'ADLBH_STD'
EXCEPT
SELECT name
FROM Dictionary.columns
WHERE libname = 'WORK'
AND memname = 'LB_STEP_14'
;
QUIT;



/*Step 15 Compare the ADLBH_STEP_14 and ADLBH_STD*/
PROC SORT DATA = LB_STEP_14;
	BY STUDYID USUBJID PARAMCD VISITNUM AVISITN;
RUN;

PROC SORT DATA = ADLBH_STD;
	BY STUDYID USUBJID PARAMCD VISITNUM AVISITN;
RUN;

PROC COMPARE BASE = ADLBH_STD COMPARE = LB_STEP_14;
	ID STUDYID USUBJID PARAMCD VISITNUM AVISITN;
RUN;

/*Step 16 QC*/

PROC COMPARE BASE = ADLBH_STD COMPARE = LB_STEP_14 NOPRINT OUT = CMP_OUT 
OUTNOEQUAL OUTBASE OUTCOMP OUTDIF;
  ID STUDYID USUBJID PARAMCD VISITNUM AVISITN;
  VAR AVAL ABLFL BASE CHG A1LO A1HI;
RUN;

PROC PRINT DATA = CMP_OUT (OBS = 1000);
RUN;




PROC COMPARE BASE = ADLBH_STD COMPARE = LB_STEP_14 NOPRINT OUT = CMP_OUT_RATIO 
OUTNOEQUAL OUTBASE OUTCOMP OUTDIF;
  ID STUDYID USUBJID PARAMCD VISITNUM AVISITN;
  VAR AVAL ALBTRVAL ANL01FL;
RUN;

PROC PRINT DATA = CMP_OUT_RATIO (OBS = 1000);
RUN;



PROC CONTENTS DATA = adlbh_std;
RUN;

PROC CONTENTS DATA = LB_STEP_14;
RUN;


LIBNAME ADAM "/home/u63793342/sasuser.v94";

DATA ADAM.ADLBH_V1;
	SET LB_STEP_14;
RUN;